### ISSUE TITLE
Request to support `wraps`

### ISSUE THREAD

**Issue by shamlian** [tekktrik/CircuitPython_functools#3]
Hello,

I'm working to make the [Python SDK for Root and Create robots](https://github.com/iRobotEducation/irobot-edu-python-sdk/tree/main) support CircuitPython. In particular, we make use of `functools.wraps()`; there is a (very) minimal implementation for [MicroPython](https://pypi.org/project/micropython-functools/) that we can work with. Is there any plan for parity between these libraries? Would a PR be friendly?

Thanks in advance.

**Comment by tekktrik** [comment]
That's rad!  Yeah, I can add in the functionality!  I think something like the MicroPython implementation is sufficient as a sort of no-op and makes the most sense.  I can have that in tonight!

**Comment by shamlian** [comment]
Awesome, thank you so much! I agree that approach should work -- I have it prototyped and working with 
```
    from functools import wraps
except ImportError:
    def wraps(wrapped, assigned=None, updated=None):
        return lambda x: x
```
but of course having the function defined inside the library (and optionally importing it in as functools instead) is more elegant.
